# config/training/ffcv.yaml
optimizer:
  name: "sgd"
  lr: 0.5
  momentum: 0.9
  weight_decay: 5e-4
  nesterov: false
  # Remove AdamW specific params since we're using SGD
  # betas: [0.9, 0.999]
  # eps: 1e-8

scheduler:
  name: "custom_triangular"
  # Remove OneCycle and Cosine specific params
  peak_epoch: 5
  initial_lr: 0.0
  peak_lr: 0.5
  final_lr: 0.0

seed: 42
epochs: 24
batch_size: 512
num_workers: 8
label_smoothing: 0.1
lr_tta: true
mixed_precision: true
gradient_clip: 0.0