# config/config.yaml
defaults:
  - _self_
  - dataset: cifar10
  - model: compare
  - training: default

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

project:
  name: "stacked-generalization"
  tags: ["baseline"]
  notes: "Initial training setup"

