# config/model_search_config.yaml
defaults:
  - _self_
  - dataset: cifar10
  - search_space: sgd  # or adamw for optimizer search space
  - training: default

hydra:
  run:
    dir: outputs/model_search/${now:%Y-%m-%d}/${now:%H-%M-%S}

project:
  name: "stacked-generalization-model-search"
  tags: ["complete-experiment-v3"]
  notes: "How important is image_features_dim"

# Base configuration that will be modified for each experiment
model:
  meta_learner:
    hidden_dims: [512, 256, 128]
    dropout_rate: 0.5
  alpha: 1.0
  init_method: "xavier_uniform"
  base_learners:
    - architecture: "resnet9"
      pretrained: false
    - architecture: "resnet9"
      pretrained: false
    - architecture: "resnet9"
      pretrained: false
  image_features_dim: 128

# Experiment configurations
experiments:
  image_features_dim_study:
    variants:
      - name: "image_features_dim_16"
        value: 16
      - name: "image_features_dim_32"
        value: 32
      - name: "image_features_dim_64"
        value: 64
      - name: "image_features_dim_128"
        value: 128
      - name: "image_features_dim_256"
        value: 256
      
  
  
  
  

# Hyperparameter search settings
optuna:
  n_trials: 10
  timeout: 72000  # 20 hours
  n_startup_trials: 3
  n_warmup_steps: 10
  pruning:
    min_delta: 0.1
    patience: 5

# Optional: specify which experiment to run
# run_experiment: "alpha_study"  # Uncomment to run specific experiment