# config/search_space/adamw.yaml
optimizer:
  name: "adamw"  # fixed
  lr:
    type: "float"
    low: 1e-5
    high: 1e-3
    log: true
  weight_decay:
    type: "float"
    low: 1e-5
    high: 1e-2
    log: true

scheduler:
  name:
    type: "categorical"
    choices: ["onecycle", "cosine", "linear"]
  pct_start:
    type: "float"
    low: 0.2
    high: 0.4
