# config/search_space/sgd.yaml
optimizer:
  name: "sgd"  # fixed
  lr:
    type: "float"
    low: 0.01
    high: 1.0
    log: true
  weight_decay:
    type: "float"
    low: 1e-5
    high: 1e-2
    log: true
  momentum:
    type: "float"
    low: 0.85
    high: 0.95
  nesterov:
    type: "categorical"
    choices: [true, false]

scheduler:
  name:
    type: "categorical"
    choices: ["onecycle", "cosine", "linear"]
  pct_start:
    type: "float"
    low: 0.2
    high: 0.4


